// DR-25: demo oracle for faux mode in the SERVER (not just E2E).
// A fresh container with MODEL_MODE=faux drives the whole flow without a model server:
// deterministic split → inspect diffs → write verdicts → guarded
// completion → summary. Driven by orchestrator phase events.
// Air-gap-friendly demo path only; ollama/remote modes never touch this.

import { fauxAssistantMessage, fauxToolCall } from "@earendil-works/pi-ai/providers/faux";
import { fauxHandle, type RuntimeConfig } from "./agent/runtime.js";
import type { Store } from "./store.js";
import type { Run } from "./types.js";
import type { RunEvents } from "./orchestrator.js";

export function installDemoOracle(store: Store, runId: string, config: RuntimeConfig): RunEvents | undefined {
  const faux = fauxHandle(config);
  if (!faux) return undefined;
  const fresh = () => store.get(runId) as Run;
  const st = { phase: "tasks" as "tasks" | "done", taskId: "" };

  const oracle = (context: any) => {
    const run = fresh();
    const toolResults = (context.messages ?? []).filter((m: any) => m.role === "toolResult");

    // ---- completion: summary then guarded close ----
    if (st.phase === "done") {
      if (!run.completionSummary) {
        const results = run.tasks.flatMap((t) => t.results);
        const applied = results.filter((r) => r.verdict === "correctly_applied").length;
        const missing = results.filter((r) => r.verdict === "missing").length;
        const needs = results.filter((r) => r.verdict === "needs_user").length;
        return fauxAssistantMessage(
          [fauxToolCall("writeRunSummary", {
            summary: `${run.summary.commentCount} comments verified: ${applied} correctly applied, ${missing} missing, ${needs} needs_user.Generated by demo oracle (faux mode).`,
          })],
          { stopReason: "toolUse" }
        );
      }
      return fauxAssistantMessage([fauxToolCall("completeRun", {})], { stopReason: "toolUse" });
    }

    // ---- task session (phase "tasks") ----
    const task = run.tasks.find((t) => t.taskId === st.taskId) ?? run.tasks.find((t) => t.status !== "done");
    if (!task) return fauxAssistantMessage("no open task"); // defensive; should not happen

    // task: diffs first, then verdicts from collected evidence, then complete
    const allWritten = task.commentNumbers.every((n) => task.results.some((r) => r.commentNumber === n));

    if (toolResults.length === 0) {
      // step 1: inspect the diff for every comment in scope
      return fauxAssistantMessage(
        task.commentNumbers.map((n) => fauxToolCall("getDiff", { commentNumber: n })),
        { stopReason: "toolUse" }
      );
    }
    if (!allWritten) {
      // step 2: write verdicts from the evidence the agent collected
      const calls = task.commentNumbers.map((n) => {
        const anchor = run.anchors.find((a) => a.commentNumber === n)!;
        const hunk =
          anchor.anchorIndex === null
            ? undefined
            : run.diff.find(
                (h) => h.beforeIndex === anchor.anchorIndex || h.afterIndex === anchor.anchorIndex
              );
        const verdict = !anchor || anchor.anchorIndex === null ? "needs_user"
          : hunk ? "correctly_applied" : "missing";
        return fauxToolCall("writeResult", {
          commentNumber: n,
          verdict,
          evidence: hunk
            ? `diff ${hunk.id}: "${(hunk.beforeText ?? "").slice(0, 60)}" → "${(hunk.afterText ?? "").slice(0, 60)}"`
            : anchor.anchorIndex === null
              ? "anchoring failed"
              : `no diff hunk at anchor block ${anchor.anchorIndex} (register says processed=yes)`,
          confidence: "high",
        });
      });
      return fauxAssistantMessage(calls, { stopReason: "toolUse" });
    }
    // step 3: guarded completion
    return fauxAssistantMessage(
      [fauxToolCall("completeTask", { note: "all comments verified (demo oracle)" })],
      { stopReason: "toolUse" }
    );
  };

  faux.setResponses(Array.from({ length: 200 }, () => oracle));
  return {
    onTaskStart: (taskId) => { st.phase = "tasks"; st.taskId = taskId; },
    onCompleteStart: () => { st.phase = "done"; },
  };
}
